### ISSUE TITLE
shap compare Funktion von 2 Modellen mit identischem Input

### ISSUE THREAD

**Issue by AndyWheel** [CloseChoice/easyshap#1]
eshap_compare(model_1, model_2, X, ...)

Output ist z.B. die shap differenzen der features

Um den Effekt eines Retrainings zu prüfen!

**Comment by CloseChoice** [comment]
Dies ist doch bloß:

```python
def eshap_compare(model1, model2, X):
    explainer = shap.<ExplainerType>Explainer(model)
    shap_values1 = explainer.shap_values(X)
    shap_values2 = explainer.shap_values(X)
    return shap_values2 - shap_values1
```
oder?

**Comment by AndyWheel** [comment]
:-D ja, halt mit 2 verschiedenen explainern. bin mir nur nicht sicher ob jede Differenz sich so einfach bilden lässt

Interessant ist zum einen die Differenz .. aber auch um wieviel % ein Feature wichtiger ist .. eventuell auch der vergleich von mehr als 2 Modellen

Ein Plot der einen Überblick schafft wäre auch interessant (wobei vllt eher eine neue Funktion)

**Comment by CloseChoice** [comment]
Vorgehen:
1. Titanic Datensatz mit Random Forest vs. XGBoost. Output ist irgendwas mit Shapvalues + Feature Name (dataframe)
2. LSTM mit Zeitachse (Inputshape[#zeit, #werte]). Shaptensor [#zeit, #werte, shapwerte]
3. LSTM mit Zeitachse, Attributen und Features (Inputshape [#zeitachse, #attribute, #feature]. Output ist ein Shaptensor mit shape [
4. LSTM + Embedding mit Attributen, Zeitachse Features als getrennte Inputs

pd.DataFrame(data, columns=[], index=[])

data.shape == [3, 10, 5]  # observations, features, time
st = Shaptensor(data, axes={0: ["observation0", "observation"...], 1: ["feature1", "feature2", ...], 2: ["2023-01-01", "2023-01-03"]})

st[:, ["feature1", "feature2"], :]

**Comment by AndyWheel** [comment]
Zu 1.: https://github.com/CloseChoice/easyshap/blob/main/shap_random_forest_example.ipynb

habe die Feature Importance mit verschiedenen Modellen berechnet und verglichen.

**Comment by CloseChoice** [comment]
Ok, habe was gefunden was den shaptensor implementiert: https://github.com/pydata/xarray. Würde vorschlagen, dass wir genau das benutzen. Ich würde sagen, dass wir einen xarray reingeben und dann auch einen erhalten.

**Comment by CloseChoice** [comment]
Dies ist implementiert durch #6 und erweitert durch #7
